<?php
  return  array(
    //Labels Botões Defaults
    'btn_novo'                                => 'Novo Registro',
    'btn_salvar'                              => 'Salvar',
    'btn_voltar'                              => 'Voltar',
    'btn_cancelar'                            => 'Cancelar',
    'btn_excluir'                             => 'Excluir',
    //Labels Defaults
    'acoes'                                   => 'Ações',
    'id'                                      => 'Id',
    'codigo'                                  => 'Código',
    'codigo_placeholder'                      => 'Digite o Código',
    'nome'                                    => 'Nome',
    'nome_placeholder'                        => 'Digite seu Nome',
    'telefone'                                => 'Telefone',
    'telefone_placeholder'                    => 'Digite seu telefone',
    'mensagem'                                => 'Mensagem',
    'email'                                   => 'E-Mail',
    'email_placeholder'                       => 'Digite um e-mail válido',
    'unidade'                                 => 'Unidade',
    'unidade_placeholder'                     => 'Selecione uma das unidades disponíveis',
    'descricao'                               => 'Descrição',
    'descricao_placeholder'                   => 'Digite a Descrição',
    'valor'                                   => 'Valor',
    'valor_placeholder'                       => 'Digite o Valor',
    'url'                                     => 'URL',
    'imagem'                                  => 'Imagem',
    'url_placeholder'                         => 'Digite o Link para o site',
    'status'                                  => 'Status',
    'data_criacao'                            => 'Dt. Criação',
    'data_edicao'                             => 'Dt. Edição',
    'data_exclusao'                           => 'Dt. Exclusão',
    'usuario_criou'                           => 'Usuário que Criou',
    'usuario_editou'                          => 'Usuário que Editou',
    'usuario_excluiu'                         => 'Usuário que Excluiu',
    //Labels Usuario
    'usuarios_selecionar'                      => 'Selecionar Usuário',
    'usuarios_cadastrar'                       => 'Cadastrar Usuário',
    'usuarios_editar'                          => 'Editar Usuário',
    'usuarios_email'                           => 'E-Mail',
    'usuarios_email_placeholder'               => 'Digite um e-mail válido',
    'usuarios_cargo'                           => 'Cargo / Função',
    'usuarios_cargo_placeholder'               => 'Digite o Cargo do Usuário',
    'usuarios_descricaoCargo'                  => 'Descrição do Cargo',
    'usuarios_redessociais'                    => 'Redes Sociais',
    'usuarios_linkedin_placeholder'            => 'Copie e cole aqui a URL do seu profile do LinkedIn',
    'usuarios_twitter_placeholder'             => 'Copie e cole aqui a URL do seu profile do Twitter',
    'usuarios_facebook_placeholder'            => 'Copie e cole aqui a URL do seu profile do Facebook',
    'usuarios_instagram_placeholder'           => 'Copie e cole aqui a URL do seu profile do Instagram',
    'usuarios_senha'                           => 'Senha',
    //Labels Modulos
    'modulo_selecionar'                       => 'Selecionar Módulo',
    'modulo_cadastrar'                        => 'Cadastrar Módulo',
    'modulo_editar'                           => 'Editar Módulo',
    'modulo'                                  => 'Módulo',
    //Labels Links Uteis
    'linksUteis_selecionar'                   => 'Selecionar Link Útil',
    'linksUteis_cadastrar'                    => 'Cadastrar Link Útil',
    'linksUteis_editar'                       => 'Editar Link Útil',
    'linkUtil'                                => 'Módulo',
    //Labels Parâmetros Globais
    'parametroGlobal_selecionar'              => 'Selecionar Parâmetro Global',
    'parametroGlobal_cadastrar'               => 'Cadastrar Parâmetro Global',
    'parametroGlobal_editar'                  => 'Editar Parâmetro Global',
    'parametroGlobal_valor_placeholder'       => 'Digite o valor do parâmetro global, pode ser um texto, um número ou um html por exemplo',
    //Labels Serviços
    'servicos_selecionar'                   => 'Selecionar Serviço',
    'servicos_cadastrar'                    => 'Cadastrar Serviço',
    'servicos_editar'                       => 'Editar Serviço',
    'servicos_pai'                          => 'Serviço Pai',
    'servicos_vinculo'                      => 'Vínculo',
    'servicos_url_servico'                  => 'URL Site Serviço Externo',
    'servicos_url_placeholder'              => 'Digite uma URL válida para o serviço externo',
    'servicos_link_servico_hint'            => 'Clique para abrir a página do serviço',
    //Labels Parceiros
    'parceiros_selecionar'                  => 'Selecionar Parceiro',
    'parceiros_cadastrar'                   => 'Cadastrar Parceiro',
    'parceiros_editar'                      => 'Editar Parceiro',
    'parceiros_indexibir'                   => 'Exibir Parceiro na Seção de Parceiros do Site?',
     //Contatos
     'contato_mensagem'                     => 'Mensagem',
     'contato_mensagem_placeholder'         => 'Digite uma mensagem para que possamos ajudar você da melhor forma possível',
     'contato_assunto'                      => 'Assunto',
     'contato_assunto_placeholder'          => 'Selecione o assunto desejado',
     'contato_titulo'                       => 'Entre em contato conosco ',
     'contato_subtitulo'                    => 'Fique à vontade em preencher o formulário abaixo',
     'contato_caixa_entrada'                => 'Caixa de Entrada',
     'contato_caixa_entrada_de'             => 'De',
     'contato_caixa_entrada_data_envio'     => 'Data de Envio',
     'contato_caixa_entrada_modal_titulo'   => 'Mensagem de: ',
     'contato_caixa_entrada_modal_titulo'   => 'Marcar Como Lida',
     'contato_abrir_msgs_lidas'             => 'Abrir Mensagens Visualizadas',
     'contato_abrir_msgs_n_lidas'           => 'Abrir Mensagens Não Lidas',

  );
