<?php
  return  array(
    //Labels Botões Defaults
    'btn_novo'                                => 'Novo Registro',
    'btn_salvar'                              => 'Salvar',
    'btn_voltar'                              => 'Voltar',
    'btn_cancelar'                            => 'Cancelar',
    'btn_excluir'                             => 'Excluir',
    //Labels Defaults
    'acoes'                                   => 'Ações',
    'id'                                      => 'Id',
    'nome'                                    => 'Nome',
    'nome_placeholder'                        => 'Digite o Nome',
    'descricao'                               => 'Descrição',
    'status'                                  => 'Status',
    'data_criacao'                            => 'Dt. Criação',
    'data_edicao'                             => 'Dt. Edição',
    'data_exclusao'                           => 'Dt. Exclusão',
    'usuario_criou'                           => 'Usuário que Criou',
    'usuario_editou'                          => 'Usuário que Editou',
    'usuario_excluiu'                         => 'Usuário que Excluiu',
    //Labels Usuario
    'usuario_selecionar'                      => 'Selecionar Usuário',
    'usuario_cadastrar'                       => 'Cadastrar Usuário',
    'usuario_editar'                          => 'Editar Usuário',
    //Labels Nivel Estudo
    'nivel_estudo_selecionar'                 => 'Selecionar Nível de Estudo',
    'nivel_estudo_cadastrar'                  => 'Cadastrar Nível de Estudo',
    'nivel_estudo_editar'                     => 'Editar Nível de Estudo',
    //Labels Modulos
    'modulo_selecionar'                       => 'Selecionar Módulo',
    'modulo_cadastrar'                        => 'Cadastrar Módulo',
    'modulo_editar'                           => 'Editar Módulo',
    //Label para Paises
    'pais_selecionar'                         => 'Selecionar País',
    'pais_cadastrar'                          => 'Cadastrar País',
    'pais_editar'                             => 'Editar País',
    'pais_nome_global'                        => 'Nome Global',
    'pais_nome_nacional'                      => 'Nome Traduzido',
    'pais_sigla'                              => 'Sigla',
    'pais_bacen'                              => 'Código do banco Central',
    'pais_nome_global_placeholder'            => 'Digite o nome global. Ex. Brazil',
    'pais_nome_nacional_placeholder'          => 'Digite o Nome traduzido em PT_BR. Ex. Brasil',
    'pais_sigla_placeholder'                  => 'Digite a sigla',
    'pais_bacen_placeholder'                  => 'Digite o código do banco central',
    //Labels para Estados
    'estado_selecionar'                       => 'Selecionar Estado',
    'estado_cadastrar'                        => 'Cadastrar Estado',
    'estado_editar'                           => 'Editar Estado',
    'estado_uf'                               => 'UF',
    'estado_id_ibge'                          => 'Código IBGE',
    'estado_pais'                             => 'País',
    'estado_ddd'                              => 'DDD',
    'estado_uf_placeholder'                   => 'Digite a sigla para UF',
    'estado_id_ibge_placeholder'              => 'Digite o Código IBGE',
    'estado_pais_placeholder'                 => 'Selecione o País',
    'estado_ddd_placeholder'                  => 'Digite o(s) código(s) para DDD separados por vírgula',
    //Labels para Cidade
    'cidade_selecionar'                       => 'Selecionar Cidade',
    'cidade_cadastrar'                        => 'Cadastrar Cidade',
    'cidade_editar'                           => 'Editar Cidade',
    'cidade_uf'                               => 'UF',
    'cidade_id_ibge'                          => 'Código IBGE',
    'cidade_ddd'                              => 'DDD',
    'cidade_uf_placeholder'                   => 'Selecione o Estado Desejado',
    'cidade_id_ibge_placeholder'              => 'Digite o Código IBGE',
    'cidade_ddd_placeholder'                  => 'Digite o DDD',
    //Labels para Logradouros
    'logradouro_selecionar'                   => 'Selecionar Logradouro',
    'logradouro_cadastrar'                    => 'Cadastrar Logradouro',
    'logradouro_editar'                       => 'Editar Logradouro',
    'logradouro_cep'                          => 'CEP',
    'logradouro_tipo'                         => 'Tipo',
    'logradouro_nome'                         => 'Logradouro',
    'logradouro_nr'                           => 'Número',
    'logradouro_cidade'                       => 'Cidade',
    'logradouro_uf'                           => 'Estado',
    'logradouro_complemento'                  => 'Complemento',
    'logradouro_nome_sem_numero'              => 'Logradouro (sem número)',
    'logradouro_id_ibge_cidade'               => 'Id IBGE da Cidade',
    'logradouro_bairro'                       => 'Bairro',
    'logradouro_origem_registro'              => 'Origem do Cadastro',
    'logradouro_cep_placeholder'              => 'Digite o CEP',
    'logradouro_tipo_placeholder'             => 'Selecione o tipo de logradouro',
    'logradouro_nome_placeholder'             => 'Digite o nome do logradouro',
    'logradouro_nr_placeholder'               => 'Digite o número',
    'logradouro_cidade_placeholder'           => 'Selecione a cidade',
    'logradouro_uf_placeholder'               => 'selecione a uf',
    'logradouro_complemento_placeholder'      => 'Digite um complemento',
    'logradouro_nome_sem_numero_placeholder'  => 'Digite o nome do logradouro SEM número',
    'logradouro_id_ibge_cidade_placeholder'   => 'Digite o numero do id ibge cidade',
    'logradouro_bairro_placeholder'           => 'Digite o Bairro',
    'logradouro_origem_registro_placeholder'  => 'Selecione a origem do registro'
  );
